sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

before_script:
  - npm install

script:
  - npm run build --prod --aot

deploy:
  skip_cleanup: true
  provider: script
  script: s3cmd --access_key="${AWS_ACCESS_KEY_ID}" --secret_key="${AWS_SECRET_ACCESS_KEY}" --region=ap-southeast-1 sync --delete-removed --acl-public --guess-mime-type --no-mime-magic --recursive public/ s3://www.skycoin.net/cx/
  on:
    branch: master

after_deploy:
- s3cmd --access_key="${AWS_ACCESS_KEY_ID}" --secret_key="${AWS_SECRET_ACCESS_KEY}" --region=ap-southeast-1 ls s3://www.skycoin.net/cx/
